# Generated by Django 5.1.1 on 2026-01-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('document', models.CharField(max_length=20, verbose_name='DNI/CUIT')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('course_id', models.CharField(max_length=100, verbose_name='ID del curso')),
                ('course_title', models.CharField(max_length=255, verbose_name='Título del curso')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de pago MP')),
                ('preference_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de preferencia MP')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('in_process', 'En proceso'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
